# ruff: noqa: E501
"""Init phase: scaffold scripts/ + compliance/ directories alongside ROBOT.md.

EU AI Act compliance evidence has to live somewhere reproducible. When
`robot-md init` creates a new ROBOT.md, this phase drops:

- ``scripts/demo-eu-ai-act.sh`` — parameterized end-to-end demo that
  emits FRIA + IFU + safety-benchmark + incidents-report, exercises the
  MCP safety gate, verifies the audit chain, and aggregates the Art-11
  summary. Manifest path comes from $MANIFEST so the script is portable
  across robots.
- ``compliance/`` — output directory the demo writes signed artifacts
  into (gitignored placeholder via .gitkeep). Lives alongside ROBOT.md
  so a notified-body submission can be assembled from a single tree.
- ``compliance/README.md`` — minimal pointer documenting what each file
  in the directory is and how to regenerate it.

Phase is idempotent: existing scripts/compliance dirs are left alone, and
the demo script is overwritten only with --force-scripts (off by default
in the orchestrator). This protects operator customisations.
"""

from __future__ import annotations

from pathlib import Path

from robot_md.init_phases import PhaseResult

DEMO_SCRIPT_TEMPLATE = """\
#!/usr/bin/env bash
# Demo: end-to-end EU AI Act evidence chain for the robot declared by
# $MANIFEST. Generated by `robot-md init`.
#
# Shows:
#   1. Manifest -> emitted artifacts (FRIA, IFU, safety-benchmark,
#      incidents report)
#   2. Capability invocation through the MCP safety gate -> audit entry
#   3. Hash-chained audit log records every safety-relevant decision
#   4. `audit verify` walks the chain and confirms integrity
#   5. Art-11 summary aggregates everything for notified-body submission
#
# This script is non-destructive (writes only to ./compliance/ and the
# ~/.robot-md state dirs). Pass --reset-audit to clear the per-robot
# audit + incidents logs before running.

set -euo pipefail

MANIFEST="${MANIFEST:-$(dirname "$0")/../ROBOT.md}"
OUT_DIR="${OUT_DIR:-$(dirname "$0")/../compliance}"
RESET_AUDIT="${1:-}"

if [ ! -f "$MANIFEST" ]; then
  echo "error: $MANIFEST does not exist (set MANIFEST=...)" >&2
  exit 2
fi

RRN=$(robot-md render "$MANIFEST" \\
  | python3 -c 'import sys,yaml; d=yaml.safe_load(sys.stdin); print((d.get("metadata") or {}).get("rrn",""))')
if [ -z "$RRN" ]; then
  echo "error: $MANIFEST has no metadata.rrn -- register the robot first" >&2
  exit 2
fi

echo "=== EU AI Act evidence demo ==="
echo "  manifest: $MANIFEST"
echo "  rrn:      $RRN"
echo "  out_dir:  $OUT_DIR"
echo

mkdir -p "$OUT_DIR"
rm -f "$OUT_DIR"/*.json

if [ "$RESET_AUDIT" = "--reset-audit" ]; then
  echo "[reset] clearing audit + incidents logs for $RRN"
  rm -f ~/.robot-md/audit/"$RRN".jsonl ~/.robot-md/incidents/"$RRN".jsonl
fi

echo "[0/6] pre-flight: robot-md compliance status"
# Surface keystore/audit/artifact/RRF blockers BEFORE the demo so the operator
# sees what's about to fail (e.g. apikey-gated --submit paths) up front.
# --no-probe in CI; remove for live RRF check. Exit 4 = blockers present;
# we DON'T abort — the demo runs to completion to validate the flow shape.
robot-md compliance status "$MANIFEST" || true
echo

echo "[1/6] emit FRIA (Art. 27)"
robot-md emit-fria "$MANIFEST" \\
  --deployment-context "demo-$(date -u +%Y-%m-%d)" \\
  -o "$OUT_DIR/fria.json"

echo "[2/6] emit IFU (Art. 13(3))"
robot-md emit-ifu "$MANIFEST" -o "$OUT_DIR/ifu.json"

echo "[3/6] emit safety benchmark (rcan-spec §23)"
robot-md emit-benchmarks "$MANIFEST" -o "$OUT_DIR/safety-benchmark.json"

echo "[4/6] record + emit incidents report (Art. 72)"
robot-md incidents record "$MANIFEST" \\
  --severity other \\
  --category demo_event \\
  --description "demo: simulated safety event"
robot-md incidents report "$MANIFEST" -o "$OUT_DIR/incidents.json"

echo "[5/6] aggregate Art. 11 technical-doc summary"
robot-md emit-art11 "$MANIFEST" \\
  --artifacts-dir "$OUT_DIR" \\
  -o "$OUT_DIR/art11.json"

echo "[6/6] verify the hash-chained audit log"
robot-md audit verify "$MANIFEST"

echo
echo "=== artifacts in $OUT_DIR/ ==="
ls -la "$OUT_DIR"/

echo
echo "Done. To submit to RRF (requires apikey at ~/.robot-md/keys/$RRN.apikey):"
echo "  for f in fria ifu safety-benchmark; do"
echo "    robot-md emit-\\$f \\"$MANIFEST\\" --sign --submit -o \\"$OUT_DIR/\\$f-signed.json\\""
echo "  done"
echo "  robot-md incidents report \\"$MANIFEST\\" --sign --submit -o \\"$OUT_DIR/incidents-signed.json\\""
"""

COMPLIANCE_README = """\
# compliance/

EU AI Act evidence for this robot. Output of `scripts/demo-eu-ai-act.sh`.

## Files

| File | Schema | EU AI Act tie-in |
|---|---|---|
| `fria.json` | `rcan-fria-v1` | Article 27 — Fundamental Rights Impact Assessment |
| `ifu.json` | `rcan-ifu-v1` | Article 13(3) — Instructions for Use |
| `safety-benchmark.json` | `rcan-safety-benchmark-v1` | rcan-spec §23 (estop / bounds / confidence-gate timing) |
| `incidents.json` | `rcan-incidents-v1` | Article 72 — Post-market monitoring |
| `art11.json` | `robot-md-art11-summary-v0` | Article 11 — Technical documentation aggregator |

The Art-11 summary's `notified_body_submission.artifacts` inventories
which signed artifacts are present here, and `notified_body_submission.
missing_artifacts` flags any gap.

## Regenerating

```bash
./scripts/demo-eu-ai-act.sh --reset-audit
```

## Submitting to RRF

Each artifact has a corresponding RRF v2 endpoint:

| Artifact | Endpoint |
|---|---|
| `fria.json` | `POST /v2/robots/<rrn>/fria` |
| `ifu.json` | `POST /v2/robots/<rrn>/ifu` |
| `safety-benchmark.json` | `POST /v2/robots/<rrn>/safety-benchmark` |
| `incidents.json` | `POST /v2/robots/<rrn>/incident-report` |

Add `--sign --submit` to any `emit-*` command (or `incidents report`) to
sign + POST in one step. Submit attempts are recorded in the local
hash-chained audit log (`robot-md audit verify`).
"""


def phase_compliance_scaffold(
    manifest_path: Path,
    *,
    force_scripts: bool = False,
) -> PhaseResult:
    """Create scripts/demo-eu-ai-act.sh + compliance/ alongside the manifest.

    Idempotent: existing files are left alone unless force_scripts=True
    (operator customisations are protected).
    """
    base = manifest_path.parent
    scripts_dir = base / "scripts"
    compliance_dir = base / "compliance"
    demo_path = scripts_dir / "demo-eu-ai-act.sh"
    readme_path = compliance_dir / "README.md"
    gitkeep_path = compliance_dir / ".gitkeep"

    created: list[str] = []
    skipped: list[str] = []

    scripts_dir.mkdir(parents=True, exist_ok=True)
    compliance_dir.mkdir(parents=True, exist_ok=True)

    if demo_path.exists() and not force_scripts:
        skipped.append(str(demo_path.relative_to(base)))
    else:
        demo_path.write_text(DEMO_SCRIPT_TEMPLATE)
        demo_path.chmod(0o755)
        created.append(str(demo_path.relative_to(base)))

    if readme_path.exists() and not force_scripts:
        skipped.append(str(readme_path.relative_to(base)))
    else:
        readme_path.write_text(COMPLIANCE_README)
        created.append(str(readme_path.relative_to(base)))

    if not gitkeep_path.exists():
        gitkeep_path.write_text("")
        created.append(str(gitkeep_path.relative_to(base)))

    return PhaseResult(
        phase="compliance_scaffold",
        status="ok",
        message=(
            f"created {len(created)} file(s), skipped {len(skipped)} existing"
            if created
            else "all scaffold files already present"
        ),
        detail={"created": created, "skipped": skipped},
    )
