"""SP-AN Task 5: the bundled CLI mirror of using-robot-md.SKILL.md
contains the three new sections + the contract phrasings the harness
tests in Tasks 7-10 will look up.

The canonical source is ~/robot-md-mcp/skills/using-robot-md/SKILL.md
(per simplification-revisions Rev 7); the mirror is regenerated by
scripts/sync-skill.sh.
"""

from __future__ import annotations

from pathlib import Path


_MIRROR = (
    Path(__file__).parents[2] / "src" / "robot_md" / "skills" / "using-robot-md.SKILL.md"
)


def test_mirror_contains_three_new_sections() -> None:
    text = _MIRROR.read_text()
    assert "## Reacting to hot-plug events" in text
    assert "## Modality hierarchy" in text
    assert "## Resolved-elsewhere handling" in text


def test_mirror_announces_30s_undo_window() -> None:
    text = _MIRROR.read_text()
    assert "30 s" in text or "30 seconds" in text


def test_mirror_describes_hotplug_review_and_confirm_calls() -> None:
    text = _MIRROR.read_text()
    assert "hotplug_review" in text
    assert "hotplug_confirm" in text
